name: postprocessing
channels: 
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.26
  - pytest
  - jupyter
  - matplotlib
  - netcdf4
  - pandas
  - pandoc
  - nose2
  - scipy
  - sphinx
  - sphinx-automodapi
  - nbsphinx
  - sphinx_rtd_theme
  - nbsphinx-link
  - xarray
